Repository theforeman/puppet-foreman, pull requests merged in 2018-09, with the labels that each got.

#668 Remove redundant symlink
  .fixtures.yml
Labels: Needs testing, Not yet reviewed

#667 allow puppetlabs-stdlib 5.x
  metadata.json
Labels: Needs testing, Not yet reviewed

#666 allow puppetlabs-concat 5.x
  metadata.json
Labels: Needs testing, Not yet reviewed

#665 allow puppetlabs-apt 6.x
  metadata.json
Labels: Enhancement, Needs testing

#671 Allow puppet/extlib 3
  metadata.json
Labels: Needs testing
