Repository theforeman/puppet-foreman, pull requests merged in 2018-11, with the labels that each got.

#685 Trying to fix rescue syntax in ENC script
  files/external_node_v2.rb
Labels: Bug, Needs testing

#688 Rewrite spec tests
  spec/classes/foreman_cli_discovery_spec.rb
  spec/classes/foreman_cli_openscap_spec.rb
  spec/classes/foreman_cli_remote_execution_spec.rb
  spec/classes/foreman_cli_spec.rb
  spec/classes/foreman_cli_tasks_spec.rb
  spec/classes/foreman_cli_templates_spec.rb
  spec/classes/foreman_cli_virt_who_configure_spec.rb
  spec/classes/foreman_config_ipa_spec.rb
  spec/classes/foreman_config_passenger_spec.rb
  spec/classes/foreman_config_spec.rb
  spec/classes/foreman_database_spec.rb
  spec/classes/foreman_install_spec.rb
  spec/classes/foreman_providers_spec.rb
  spec/classes/foreman_puppetmaster_spec.rb
  spec/classes/foreman_repo_spec.rb
  spec/classes/foreman_repos_extra_spec.rb
  spec/classes/foreman_service_spec.rb
  spec/classes/foreman_settings_spec.rb
  spec/classes/foreman_spec.rb
  spec/defines/foreman_config_passenger_fragment_spec.rb
  spec/defines/foreman_plugin_spec.rb
  spec/defines/foreman_rake_spec.rb
  spec/defines/foreman_repos_apt_spec.rb
  spec/defines/foreman_repos_spec.rb
  spec/defines/foreman_repos_yum_spec.rb
Labels: Needs testing, Not yet reviewed

#694 Fix wrong variable name in enc function
  files/external_node_v2.rb
Labels: Bug, Needs testing

#697 Declare Foreman group explicitly
  manifests/config.pp
Labels: Needs testing
