Repository theforeman/puppet-foreman, pull requests merged in 2019-04, with the labels that each got.

#718 Add certname to error output in external_node_v2.rb
  files/external_node_v2.rb
Labels: Needs testing, Not yet reviewed

#717 Avoid processing fact yaml files with empty 'values' hash
  files/external_node_v2.rb
Labels: Needs testing, Not yet reviewed

#725 Add Parameters for jobs_service
  manifests/init.pp
Labels: Enhancement, Needs testing

#719 drop Puppet 4
  .travis.yml
  Gemfile
  metadata.json
Labels: Backwards incompatible, Needs testing

#726 Drop support for $use_vhost
  manifests/config/apache.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_config_apache_spec.rb
  spec/classes/foreman_spec.rb
  spec/defines/foreman_config_apache_fragment_spec.rb
  templates/apache-fragment.conf.erb
  templates/foreman-apache.conf.erb
Labels: Backwards incompatible, Needs testing

#723 Refactor running with a service to Foreman 1.22
  .fixtures.yml
  README.md
  manifests/config.pp
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  manifests/service.pp
  spec/classes/foreman_service_spec.rb
  spec/classes/foreman_spec.rb
  templates/foreman.default.erb
  templates/foreman.service-overrides.erb
  templates/foreman.sysconfig.erb
Labels: Backwards incompatible, Needs testing

#727 Release 12.0.0
  CHANGELOG.md
Labels: Needs testing, Not yet reviewed

#729 Fixes #26695 - remove puppetdb_dashboard_address
  manifests/plugin/puppetdb.pp
  manifests/plugin/puppetdb/params.pp
Labels: Needs testing
