Repository theforeman/puppet-foreman, pull requests merged in 2019-11, with the labels that each got.

#768 Fixes #28200 - Change cockpit port from 9999 to 19090
  manifests/plugin/remote_execution/cockpit.pp
  spec/acceptance/foreman_rex_cockpit_spec.rb
  spec/classes/plugin/remote_execution_cockpit_spec.rb
Labels: Enhancement, Needs testing

#770 Update GHCG gem and drop rdoc
  Gemfile
Labels: Needs testing, Not yet reviewed

#767 Initial AzureRM support
  manifests/plugin/azure.pp
  spec/classes/plugin/azure_spec.rb
Labels: Needs testing

#772 Add Foreman AzureRM cli option
  manifests/cli/azure.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/foreman_cli_azure_spec.rb
Labels: Needs testing

#774 Skip the prometheus acceptance test on Debian
  spec/acceptance/foreman_prometheus_spec.rb
Labels: Needs testing, Not yet reviewed

#775 Release 13.1.0
  CHANGELOG.md
  README.md
  metadata.json
Labels: Needs testing

#777 Drop Debian 9 and Ubuntu 16.04, add Debian 10
  .sync.yml
  .travis.yml
  metadata.json
  spec/classes/foreman_cli_discovery_spec.rb
  spec/classes/foreman_cli_virt_who_configure_spec.rb
  spec/defines/foreman_repos_apt_spec.rb
Labels: Needs testing
