Repository theforeman/puppet-foreman, pull requests merged in 2019-05, with the labels that each got.

#730 Adding foreman_kubevirt Plugin
  manifests/plugin/kubevirt.pp
  spec/classes/plugin/kubevirt_spec.rb
Labels: Enhancement, Needs testing

#728 allow puppetlabs-apt 7.x and puppetlabs-postgresql 7.x
  metadata.json
Labels: Needs testing

#733 Add hammer plugin for foreman_kubevirt
  manifests/cli/kubevirt.pp
  spec/classes/foreman_cli_kubevirt_spec.rb
Labels: Needs testing

#735 Release 12.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#732 Allow `puppetlabs/stdlib` 6.x
  metadata.json
Labels: Needs testing, Not yet reviewed
