Repository theforeman/puppet-foreman, pull requests merged in 2019-12, with the labels that each got.

#778 Run migrations if there are pending migrations
  manifests/database.pp
  manifests/rake.pp
  spec/classes/foreman_database_spec.rb
  spec/classes/foreman_spec.rb
  spec/defines/foreman_rake_spec.rb
Labels: Needs testing

#781 Drop multiple database support
  README.md
  manifests/config.pp
  manifests/database.pp
  manifests/database/mysql.pp
  manifests/database/sqlite.pp
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  spec/classes/foreman_database_spec.rb
  spec/classes/foreman_spec.rb
  templates/database.yml.erb
Labels: Backwards incompatible, Needs testing

#782 Revert "Skip the prometheus acceptance test on Debian"
  spec/acceptance/foreman_prometheus_spec.rb
Labels: Needs testing

#783 Drop the selinux parameter
  manifests/config.pp
  manifests/config/apache.pp
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  spec/classes/foreman_config_apache_spec.rb
  spec/classes/foreman_config_ipa_spec.rb
  spec/classes/foreman_install_spec.rb
  spec/classes/foreman_spec.rb
  spec/defines/foreman_config_apache_fragment_spec.rb
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#785 Drop keepalive parameters
  manifests/config/apache.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_config_apache_spec.rb
  spec/classes/foreman_spec.rb
  spec/defines/foreman_config_apache_fragment_spec.rb
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#784 Drop listen_on_interface
  manifests/config/apache.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_config_apache_spec.rb
  spec/classes/foreman_spec.rb
  spec/defines/foreman_config_apache_fragment_spec.rb
Labels: Backwards incompatible, Needs testing

#786 remove mysql module from fixtures
  .fixtures.yml
Labels: Needs testing

#787 Refactor CLI plugin specs
  spec/classes/cli_plugins_spec.rb
  spec/classes/foreman_cli_ansible_spec.rb
  spec/classes/foreman_cli_azure_spec.rb
  spec/classes/foreman_cli_discovery_spec.rb
  spec/classes/foreman_cli_kubevirt_spec.rb
  spec/classes/foreman_cli_openscap_spec.rb
  spec/classes/foreman_cli_remote_execution_spec.rb
  spec/classes/foreman_cli_tasks_spec.rb
  spec/classes/foreman_cli_templates_spec.rb
  spec/classes/foreman_cli_virt_who_configure_spec.rb
Labels: Needs testing, Not yet reviewed
