Repository theforeman/puppet-foreman, pull requests merged in 2019-01, with the labels that each got.

#704 Use Bundler 1.17.3 on Ruby 2.1.9
  .travis.yml
Labels: Needs testing, Not yet reviewed

#705 fix foreman config location for ssl = false and use_vhost = false
  manifests/config/passenger.pp
Labels: Needs testing

#701 Fixes #25170 - Update admin/pass param to initial_param.
  manifests/cli.pp
  manifests/database.pp
  manifests/init.pp
  manifests/params.pp
  spec/acceptance/foreman_basic_spec.rb
  spec/acceptance/foreman_journald_spec.rb
  spec/acceptance/foreman_prometheus_spec.rb
  spec/acceptance/foreman_statsd_spec.rb
  spec/classes/foreman_cli_spec.rb
  spec/classes/foreman_database_spec.rb
  spec/classes/foreman_spec.rb
Labels: Backwards incompatible, Needs testing

#708 Remove default repo management
  manifests/init.pp
  manifests/params.pp
  manifests/repo.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/acceptance/foreman_cli_spec.rb
  spec/classes/foreman_install_spec.rb
  spec/classes/foreman_repo_spec.rb
  spec/classes/foreman_spec.rb
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#709 allow puppetlabs-apache 4.x
  metadata.json
Labels: Needs testing

#707 Fixes #25787 - Make login and taxonomy settings optional
  README.md
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
  templates/settings.yaml.erb
Labels: Backwards incompatible, Needs testing

#710 Release 11.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing

#712 Clarify the defaults switched
  README.md
Labels: Needs testing
