Repository theforeman/puppet-foreman, pull requests merged in 2019-06, with the labels that each got.

#734 Use system packages on EL8
  manifests/cli/params.pp
  manifests/params.pp
  manifests/plugin/ovirt_provision/params.pp
  manifests/plugin/puppetdb/params.pp
  manifests/plugin/tasks/params.pp
Labels: Needs testing

#737 allow newer versions of dependencies
  metadata.json
Labels: Needs testing, Not yet reviewed

#738 Release 12.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog
