Repository theforeman/puppet-foreman, pull requests merged in 2020-05, with the labels that each got.

#762 Add options for rails_cache_store
  README.md
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
  templates/settings.yaml.erb
Labels: Enhancement, Needs testing

#699 Use beaker-hiera to reduce duplication
  Gemfile
  spec/acceptance/foreman_basic_spec.rb
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/acceptance/foreman_cli_spec.rb
  spec/acceptance/foreman_journald_spec.rb
  spec/acceptance/foreman_prometheus_spec.rb
  spec/acceptance/foreman_rex_cockpit_spec.rb
  spec/acceptance/foreman_statsd_spec.rb
  spec/acceptance/hieradata/common.yaml
  spec/acceptance/hieradata/os/RedHat/7.yaml
  spec/spec_helper_acceptance.rb
Labels: Needs re-review, Needs testing

#836 Modulesync: Require voxpupuli-test 1.4
  Gemfile
  Rakefile
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Not yet reviewed

#835 Ensure Foreman is provisioned before configuring cockpit
  manifests/plugin/remote_execution/cockpit.pp
  spec/classes/plugin/remote_execution_cockpit_spec.rb
Labels: Needs testing

#828 Fixes #29212 - support el8
  .sync.yml
  .travis.yml
  metadata.json
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/foreman_spec.rb
  spec/classes/plugin/ovirt_provision_spec.rb
  spec/classes/plugin/puppetdb_spec.rb
  spec/classes/plugin/tasks_spec.rb
  spec/defines/foreman_plugin_spec.rb
Labels: Needs testing

#838 Refs #29601: Drop foreman-release-scl in favor of centos-release-scl-rh
  manifests/repo.pp
  spec/classes/foreman_repo_spec.rb
Labels: Needs testing, Not yet reviewed

#839 Prefix ipa and sssd facts with foreman_
  lib/facter/sssd.rb
  manifests/config.pp
  spec/classes/foreman_config_ipa_spec.rb
  templates/auth_kerb.conf.erb
Labels: Backwards incompatible, Needs testing

#840 Allow puppet/redis 6.x
  metadata.json
Labels: Needs testing

#844 Release 15.0.0
  CHANGELOG.md
  HISTORY.md
Labels: Needs testing, skip-changelog

#845 Switch to postgresql::postgresql_password
  manifests/database/postgresql.pp
  metadata.json
Labels: Needs testing

#846 Fixes #29892 - Use server certs for websockets
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
  templates/settings.yaml.erb
Labels: Needs testing, Not yet reviewed
