Repository theforeman/puppet-foreman, pull requests merged in 2020-06, with the labels that each got.

#848 Fixes #29649 - Prefix ipa and sssd facts with foreman_
  lib/facter/sssd.rb
  manifests/config.pp
  spec/classes/foreman_config_ipa_spec.rb
  templates/auth_kerb.conf.erb
Labels: Bug, Needs testing

#851 Fixes #30026 - Ensure Foreman is provisioned before configuring puppetdb
  manifests/plugin/puppetdb.pp
  spec/classes/plugin/puppetdb_spec.rb
Labels: Bug, Needs testing

#852 Fixes #30026 - Ensure Foreman is provisioned before puppetdb
  manifests/plugin/puppetdb.pp
  spec/classes/plugin/puppetdb_spec.rb
Labels: Bug, Needs testing

#853 Release 14.0.2
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#857 Fixes #30026 - Ensure Foreman is provisioned before puppetdb
  manifests/plugin/puppetdb.pp
  spec/classes/plugin/puppetdb_spec.rb
Labels: Needs testing, Not yet reviewed

#858 Release 15.0.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#859 fix: indent for rails_cache_store redis type
  templates/settings.yaml.erb
Labels: Bug, Needs testing
