Repository theforeman/puppet-foreman, pull requests merged in 2020-08, with the labels that each got.

#855 Add foreman_statistics plugin
  manifests/plugin/statistics.pp
  spec/classes/plugin/statistics_spec.rb
Labels: Needs testing

#601 add plugin foreman_column_view
  manifests/plugin/column_view.pp
  spec/classes/plugin/column_view_spec.rb
  templates/foreman_column_view.yaml.erb
  types/column_view_column.pp
Labels: Enhancement, Needs testing

#870 Release 15.1.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
