Repository theforeman/puppet-foreman, pull requests merged in 2020-04, with the labels that each got.

#820 Allow extlib 5.x
  metadata.json
Labels: Needs testing, Not yet reviewed

#818 add Ubuntu integration tests
  .sync.yml
  .travis.yml
Labels: Needs testing

#821 Rename inventory_upload to rh_cloud
  manifests/plugin/inventory_upload.pp
  manifests/plugin/rh_cloud.pp
  spec/classes/plugin/inventory_upload_spec.rb
  spec/classes/plugin/rh_cloud_spec.rb
Labels: Needs testing

#822 Only install foreman-release-scl on CentOS EL 7
  manifests/params.pp
Labels: Needs testing

#825 Make camptocamp/systemd a hard dependency
  README.md
  metadata.json
  spec/spec_helper_acceptance.rb
Labels: Needs re-review, Needs testing

#826 Drop the separate rails repository
  manifests/repos/yum.pp
  spec/defines/foreman_repos_yum_spec.rb
Labels: Bug, Needs re-review, Needs testing

#815 Refactor repository handling
  manifests/cli.pp
  manifests/init.pp
  manifests/params.pp
  manifests/providers.pp
  manifests/repo.pp
  manifests/repos/extra.pp
  spec/classes/foreman_cli_spec.rb
  spec/classes/foreman_install_spec.rb
  spec/classes/foreman_providers_spec.rb
  spec/classes/foreman_repo_spec.rb
  spec/classes/foreman_repos_extra_spec.rb
  spec/classes/foreman_spec.rb
  spec/setup_acceptance_node.pp
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#832 Use legacy facts for puppetmaster defaults
  manifests/puppetmaster/params.pp
Labels: Needs testing

#833 Add Leapp plugin
  manifests/plugin/leapp.pp
  spec/classes/plugin/leapp_spec.rb
Labels: Enhancement, Needs testing

#834 Switch AIO detection to use aio_agent_version fact
  manifests/params.pp
  manifests/providers/params.pp
  manifests/puppetmaster/params.pp
  spec/support/aio.rb
Labels: Needs testing, Not yet reviewed
