Repository theforeman/puppet-foreman, pull requests merged in 2020-01, with the labels that each got.

#761 Fixes #28067 - dynflow sidekiq services config
  .fixtures.yml
  Gemfile
  manifests/config.pp
  manifests/dynflow/worker.pp
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  manifests/service.pp
  metadata.json
  spec/acceptance/foreman_basic_spec.rb
  spec/acceptance/foreman_journald_spec.rb
  spec/acceptance/foreman_prometheus_spec.rb
  spec/acceptance/foreman_reverse_proxy_spec.rb
  spec/acceptance/foreman_rex_cockpit_spec.rb
  spec/acceptance/foreman_statsd_spec.rb
  spec/classes/foreman_install_spec.rb
  spec/classes/foreman_service_spec.rb
  spec/classes/foreman_spec.rb
  spec/defines/foreman_dynflow_worker_spec.rb
  spec/spec_helper_acceptance.rb
  templates/dynflow_worker.yml.erb
  templates/settings.yaml.erb
Labels: Backwards incompatible, Needs testing

#791 Refs #28067: Ensure dynflow worker config exists before service
  manifests/dynflow/worker.pp
Labels: Needs testing

#731 Fixes #26739 - Add admin users locale and timezone setting
  manifests/database.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
Labels: Needs testing, Waiting on contributor

#792 Ensure plugins are installed before the database
  manifests/init.pp
  manifests/plugin.pp
  spec/classes/foreman_spec.rb
  spec/defines/foreman_plugin_spec.rb
Labels: Needs testing
