Repository theforeman/puppet-foreman, pull requests merged in 2020-03, with the labels that each got.

#806 Correct casing on Stdlib::HTTPUrl
  lib/puppet/functions/foreman/foreman.rb
  lib/puppet/functions/foreman/smartvar.rb
  manifests/config/apache.pp
  manifests/repos/apt.pp
Labels: Needs testing

#807 Fixes #29255 - Set plugin config file mode to 0640
  manifests/plugin.pp
  spec/defines/foreman_plugin_spec.rb
Labels: Needs testing

#809 Use plugin_prefix to determine plugin packages
  manifests/plugin/ovirt_provision.pp
  manifests/plugin/ovirt_provision/params.pp
  manifests/plugin/puppetdb.pp
  manifests/plugin/puppetdb/params.pp
  manifests/plugin/tasks.pp
  manifests/plugin/tasks/params.pp
  spec/classes/plugin/ovirt_provision_spec.rb
  spec/classes/plugin/puppetdb_spec.rb
  spec/classes/plugin/tasks_spec.rb
Labels: Backwards incompatible, Needs testing

#810 Refs #28436 - Drop unused parameter
  manifests/settings.pp
Labels: Needs testing, Not yet reviewed

#811 Refs #29148: Do not proxy /pulp2 to Puma
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
Labels: Needs testing

#812 Adjust acceptance tests after switching to Puma
  spec/acceptance/foreman_basic_spec.rb
  spec/acceptance/foreman_journald_spec.rb
  spec/acceptance/foreman_prometheus_spec.rb
  spec/acceptance/foreman_statsd_spec.rb
Labels: Needs testing

#808 Bump version to 15.0.0
  metadata.json
Labels: Needs testing, skip-changelog

#814 Refs #29144 - Use systemd socket activation
  manifests/config.pp
  manifests/init.pp
  spec/classes/foreman_spec.rb
  templates/foreman.service-overrides.erb
  templates/foreman.socket-overrides.erb
Labels: Needs testing

#816 Refs #29144 - Correct socket override
  templates/foreman.socket-overrides.erb
Labels: Needs testing

#817 Refs #29144 - Use the correct ListenStream
  spec/classes/foreman_spec.rb
  templates/foreman.socket-overrides.erb
Labels: Needs testing
