Repository theforeman/puppet-foreman, pull requests merged in 2020-11, with the labels that each got.

#904 Use backwards compatible 'pattern' logging_layout by default
  manifests/params.pp
  spec/classes/foreman_spec.rb
Labels: Bug, Needs testing

#903 Release 15.1.2
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#884 CLI: make refresh_cache and request_timeout params global
  spec/classes/foreman_cli_spec.rb
  templates/hammer_etc.yml.erb
  templates/hammer_root.yml.erb
Labels: Needs testing

#905 CLI: Allow to configure use_sessions setting
  manifests/cli.pp
  manifests/cli/params.pp
  spec/classes/foreman_cli_spec.rb
  templates/hammer_etc.yml.erb
Labels: Needs testing

#883 Fixes #30803: Bind to socket for Puma and Apache
  manifests/config.pp
  manifests/config/apache.pp
  manifests/init.pp
  manifests/params.pp
  manifests/service.pp
  spec/classes/foreman_config_apache_spec.rb
  spec/classes/foreman_spec.rb
  spec/support/acceptance/examples.rb
  templates/foreman.service-overrides.erb
  templates/foreman.socket-overrides.erb
Labels: Enhancement, Needs testing

#906 Use apache::mod::auth_openidc
  manifests/config/apache.pp
  metadata.json
  spec/classes/foreman_config_apache_spec.rb
Labels: Needs testing
