Repository theforeman/puppet-foreman, pull requests merged in 2020-10, with the labels that each got.

#871 Fix comparison code in test
  spec/classes/foreman_spec.rb
Labels: Needs testing

#890 Fixes #30789 - Set DB pool size dynamically
  manifests/config.pp
  manifests/init.pp
  templates/database.yml.erb
Labels: Needs testing

#891 Release 15.0.3
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog

#872 Fixes #30535 - Set HTTP headers for proxy requests
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
  templates/lookup_identity.conf.erb
Labels: Enhancement, Needs testing

#893 Release 15.1.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#895 Drop foreman_compute that was removed in 1.22
  manifests/compute/foreman_compute.pp
Labels: Needs testing

#894 Drop Rackspace compute resource that was dropped in Foreman 2.1
  manifests/compute/rackspace.pp
Labels: Backwards incompatible, Needs testing

#847 fixes #29938 - change default logging layout
  README.md
  manifests/init.pp
  manifests/params.pp
Labels: Backwards incompatible, Needs testing

#896 Refs #30535 - Correctly unset remote user groups
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
Labels: Needs testing

#886 Set compute resource version parameter to advanced
  manifests/compute/ec2.pp
  manifests/compute/gce.pp
  manifests/compute/libvirt.pp
  manifests/compute/openstack.pp
  manifests/compute/ovirt.pp
  manifests/compute/vmware.pp
Labels: Needs testing

#897 Refs #29938: Fix failing unit tests due to logging layout change
  spec/classes/foreman_spec.rb
Labels: Needs testing

#892 Fixes #31215 - Generate DSL docs
  manifests/database.pp
  manifests/init.pp
  manifests/plugin.pp
  spec/classes/foreman_database_spec.rb
  spec/classes/foreman_spec.rb
Labels: Enhancement, Needs testing

#899 Switch to GH Actions from Travis
  .github/workflows/acceptance.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  .travis.yml
Labels: Needs testing, skip-changelog

#898 Release 16.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
