Repository theforeman/puppet-foreman, pull requests merged in 2020-02, with the labels that each got.

#798 Set ssl_verify_client parameter in tests
  spec/classes/foreman_config_apache_spec.rb
  spec/defines/foreman_config_apache_fragment_spec.rb
Labels: Needs testing

#799 Drop foreman::config::passenger::fragment
  manifests/config/passenger/fragment.pp
  spec/defines/foreman_config_passenger_fragment_spec.rb
Labels: Backwards incompatible, Needs testing

#797 Release 14.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed

#800 Make foreman::config::apache standalone
  manifests/config.pp
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
  spec/defines/foreman_config_apache_fragment_spec.rb
Labels: Needs testing

#788 Fixes #28739: Fix static asset caching when using Puma
  files/_assets.conf.erb
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
  templates/_assets.conf.erb
Labels: Bug, Needs testing

#790 Fixes #28955 - Added puma configuration
  manifests/init.pp
  manifests/params.pp
  templates/foreman.service-overrides.erb
Labels: Needs testing

#779 Fixes #28436 - Add keycloak support
  manifests/config.pp
  manifests/config/apache.pp
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  manifests/settings.pp
  spec/classes/foreman_config_apache_spec.rb
  spec/classes/foreman_spec.rb
Labels: Needs testing

#802 Fixes #29148 - Use Puma instead of Passenger by default
  manifests/params.pp
  spec/classes/foreman_service_spec.rb
  spec/classes/foreman_spec.rb
Labels: Backwards incompatible, Needs testing
