Repository theforeman/puppet-foreman, pull requests merged in 2021-08, with the labels that each got.

#977 Add hammer plugin for foreman_webhooks
  manifests/cli/webhooks.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/cli_plugins_spec.rb
Labels: Needs testing

#980 Fix beaker task
  .github/workflows/ci.yml
  Gemfile
  Rakefile
Labels: Modulesync, Needs testing

#979 Add hammer plugin for foreman_puppet
  manifests/cli/puppet.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/cli_plugins_spec.rb
Labels: Needs testing, Not yet reviewed

#983 Release 18.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#984 Fixes #33214: Set minimum Puma threads equal to maximum puma threads …
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
  templates/foreman.service-overrides.erb
Labels: Needs testing

#986 Fixes #33277: Change Puma default workers to 1.5 * CPU, max threads to 5
  manifests/config.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
  templates/foreman.service-overrides.erb
Labels: Needs testing

#988 Fixes #33320 - Refer to FQDN instead of "Foreman server" in SmartProx…
  lib/puppet/provider/foreman_resource/rest_v3.rb
  spec/unit/foreman_resource_rest_v3_spec.rb
Labels: Needs testing, Enhancement

#991 Release 18.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
