Repository theforeman/puppet-foreman, pull requests merged in 2021-03, with the labels that each got.

#918 Update Github Actions workflow
  .github/workflows/acceptance.yml
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  Gemfile
Labels: Modulesync, Needs testing, Not yet reviewed

#923 Pin camptocamp/systemd module to 2.12.0 in testing
  .fixtures.yml
Labels: Needs testing

#924 use deb gpg key from our server, not the gpg network
  manifests/repos/apt.pp
  spec/defines/foreman_repos_apt_spec.rb
Labels: Needs testing

#920 Add foreman_webhooks plugin
  manifests/plugin/webhooks.pp
  spec/classes/plugin/webhooks_spec.rb
Labels: Needs testing

#926 Fixes #32208 - accept trailing slash in Krb auth url
  templates/lookup_identity.conf.erb
Labels: Needs testing

#922 Fixes #32175: Allow toggling task backup when cleaning them up
  manifests/plugin/tasks.pp
  spec/classes/plugin/tasks_spec.rb
  templates/tasks.cron.erb
Labels: Enhancement, Needs testing
