Repository theforeman/puppet-foreman, pull requests merged in 2021-05, with the labels that each got.

#945 Make database.yml and settings.yaml have consistent headers
  templates/database.yml.erb
  templates/settings.yaml.erb
Labels: Bug, Needs testing

#947 Allow Puppet 7 compatible versions of mods
  metadata.json
Labels: Needs testing, Not yet reviewed

#953 Allow customising ProxyAddHeaders
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
Labels: Enhancement, Needs testing

#954 Switch to voxpupuli-acceptance 1.0
  Gemfile
  spec/acceptance/dynflow_spec.rb
  spec/acceptance/foreman_basic_spec.rb
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/acceptance/foreman_cli_spec.rb
  spec/acceptance/foreman_journald_spec.rb
  spec/acceptance/foreman_prometheus_spec.rb
  spec/acceptance/foreman_rex_cockpit_spec.rb
  spec/acceptance/foreman_statsd_spec.rb
  spec/spec_helper_acceptance.rb
Labels: Needs testing

#955 Allow puppet/redis 7.x
  metadata.json
Labels: Needs testing

#956 Mark compatible with camptocamp/systemd 3.x
  metadata.json
Labels: Needs testing
