Repository theforeman/puppet-foreman, pull requests merged in 2021-11, with the labels that each got.

#1000 Refs #33760 - Add host_reports plugin
  manifests/plugin/host_reports.pp
  spec/classes/plugin/host_reports_spec.rb
Labels: Needs testing, Enhancement

#996 Apply version restrictions to all packages
  manifests/install.pp
  spec/classes/foreman_spec.rb
Labels: Needs testing

#1003 Drop server_ssl_certs_dir parameter
  manifests/config.pp
  manifests/config/apache.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_config_apache_spec.rb
  spec/classes/foreman_spec.rb
Labels: Needs testing, Backwards incompatible

#981 Add Ubuntu 20.04 support & drop Ubuntu 18.04
  metadata.json
Labels: Needs testing, Enhancement

#1005 Cleanup .fixtures.yml
  .fixtures.yml
Labels: Needs testing

#1004 puppetlabs/stdlib: Allow 8.x
  metadata.json
Labels: Needs testing

#1006 puppetlabs/apache: Allow 7.x
  metadata.json
Labels: Needs testing
