Repository theforeman/puppet-foreman, pull requests merged in 2021-04, with the labels that each got.

#843 Fixes #29817 - Implement a dynflow worker pool
  lib/facter/dynflow.rb
  manifests/config.pp
  manifests/dynflow/pool.pp
  manifests/dynflow/worker.pp
  manifests/init.pp
  manifests/install.pp
  manifests/params.pp
  manifests/service.pp
  spec/acceptance/dynflow_spec.rb
  spec/classes/foreman_install_spec.rb
  spec/classes/foreman_service_spec.rb
  spec/classes/foreman_spec.rb
  spec/defines/foreman_dynflow_pool_spec.rb
  spec/defines/foreman_dynflow_worker_spec.rb
  spec/support/acceptance/examples.rb
  spec/unit/facter/dynflow_spec.rb
  templates/settings.yaml.erb
Labels: Backwards incompatible, Needs testing

#930 Mark compatible with puppetlabs/postgresql 7.x
  metadata.json
Labels: Needs testing

#932 Bump major version to 17.x
  metadata.json
Labels: Needs testing, skip-changelog

#931 Remove old email.yaml and cronjob cleanups
  manifests/config.pp
  manifests/init.pp
  spec/classes/foreman_spec.rb
Labels: Backwards incompatible, Needs testing

#933 Drop Puppetserver integration
  .sync.yml
  files/external_node_v2.rb
  files/foreman-report_v2.rb
  manifests/puppetmaster.pp
  manifests/puppetmaster/params.pp
  spec/classes/foreman_puppetmaster_spec.rb
  spec/spec_helper.rb
  spec/static_fixtures/fake.host.fqdn.com.yaml
  spec/static_fixtures/report-2.6.12-noops.yaml
  spec/static_fixtures/report-2.6.2-debug.yaml
  spec/static_fixtures/report-2.6.5-errors.yaml
  spec/static_fixtures/report-3.5.1-catalog-errors.yaml
  spec/static_fixtures/report-empty.json
  spec/static_fixtures/report-empty.yaml
  spec/static_fixtures/report-format-2.json
  spec/static_fixtures/report-format-2.yaml
  spec/static_fixtures/report-format-3.json
  spec/static_fixtures/report-format-3.yaml
  spec/static_fixtures/report-format-6.json
  spec/static_fixtures/report-format-6.yaml
  spec/static_fixtures/report-log-preprocessed.yaml
  spec/unit/foreman_external_node_spec.rb
  spec/unit/foreman_report_processor_spec.rb
Labels: Backwards incompatible, Needs testing

#937 Enable Ruby 2.7 module for EL8 on Foreman 2.5+
  manifests/repo.pp
  spec/classes/foreman_repo_spec.rb
Labels: Needs testing

#936 Refs #32276: Add Katello hammer plugin
  manifests/cli/katello.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/cli_plugins_spec.rb
Labels: Enhancement, Needs testing

#940 Release 17.0.0
  CHANGELOG.md
  HISTORY.md
Labels: Needs testing, skip-changelog

#944 Allow customising the list of HTTP headers to unset
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
Labels: Needs testing
