Repository theforeman/puppet-foreman, pull requests merged in 2021-06, with the labels that each got.

#921 Support Puppet 7
  .github/workflows/ci.yml
  metadata.json
Labels: Enhancement, Needs testing

#957 Add ACD plugin
  manifests/plugin/acd.pp
  spec/classes/plugin/acd_spec.rb
Labels: Enhancement, Needs testing

#961 Fixes #32827 - Add sendmail config options
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
  templates/settings.yaml.erb
Labels: Needs testing

#963 Bump version to 18.0.0
  metadata.json
Labels: Needs testing, skip-changelog

#938 Refs #32885: Add puppet user to user_groups only if server or client certificate contains puppet path
  manifests/config.pp
  manifests/params.pp
  spec/acceptance/hieradata/common.yaml
  spec/classes/foreman_spec.rb
Labels: Needs testing
