Repository theforeman/puppet-foreman, pull requests merged in 2021-07, with the labels that each got.

#966 Autorequire provider in smartproxy type
  lib/puppet/type/foreman_smartproxy.rb
  manifests/providers.pp
  spec/classes/foreman_providers_spec.rb
Labels: Enhancement, Needs testing

#958 Drop Puppet 5 support
  lib/puppet/functions/foreman/enc.rb
  metadata.json
Labels: Needs testing

#964 Use to_symbolized_yaml instead of a template for supervisory
  manifests/plugin/supervisory_authority.pp
  spec/classes/plugin/supervisory_authority_spec.rb
  templates/foreman_supervisory_authority.yaml.erb
Labels: Enhancement, Needs testing

#967 Fixes #32352 - use mod_auth_gssapi instead of mod_auth_kerb
  manifests/config.pp
  manifests/config/apache.pp
  spec/classes/foreman_config_ipa_spec.rb
  templates/auth_gssapi.conf.erb
Labels: Enhancement, Needs testing

#970 Remove unused suburi template
  templates/_suburi.conf.erb
Labels: Needs testing

#962 Use EPP instead of ERB for some templates
  manifests/cli.pp
  templates/hammer_etc.yml.epp
  templates/hammer_etc.yml.erb
  templates/hammer_root.yml.epp
  templates/hammer_root.yml.erb
Labels: Enhancement, Needs testing

#913 Configurable: email_reply_address, email_subject_prefix
  manifests/init.pp
  manifests/params.pp
  manifests/settings.pp
  spec/classes/foreman_spec.rb
Labels: Enhancement, Needs testing

#935 Fixes #29649 - Drop default_server argument in IPA
  lib/facter/sssd.rb
  lib/facter/util/sssd.rb
  manifests/config.pp
  spec/classes/foreman_config_ipa_spec.rb
Labels: Needs testing

#971 Match Foreman user to what packaging creates
  manifests/config.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
Labels: Needs testing

#868 added foreman_datacenter
  manifests/plugin/datacenter.pp
  spec/classes/plugin/datacenter.rb
Labels: Enhancement, Needs testing

#974 Fixes #33089 - move (hammer_)plugin_prefix to globals
  manifests/cli.pp
  manifests/cli/globals.pp
  manifests/cli/params.pp
  manifests/cli/plugin.pp
  manifests/globals.pp
  manifests/init.pp
  manifests/params.pp
  manifests/plugin.pp
  manifests/plugin/ovirt_provision.pp
  manifests/plugin/puppetdb.pp
  manifests/plugin/tasks.pp
  spec/classes/foreman_spec.rb
Labels: Backwards incompatible, Needs testing

#969 Handle duplicate file declaration for foreman::app_root
  manifests/config.pp
Labels: Needs testing

#972 Let Function to_symbolized_yaml handle Datatype Sensitive
  lib/puppet/functions/foreman/to_symbolized_yaml.rb
  spec/functions/foreman_to_symbolized_yaml_spec.rb
Labels: Needs testing, Not yet reviewed

#975 Fixes #33106 - Move user, app_root, rails_env & vhost_prio to globals
  manifests/globals.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
Labels: Backwards incompatible, Needs testing, Not yet reviewed

#976 Replace use of verify_exact_contents
  spec/classes/foreman_cli_spec.rb
Labels: Needs testing

#973 Release 18.0.0
  CHANGELOG.md
Labels: Needs testing
