Repository theforeman/puppet-foreman, pull requests merged in 2021-12, with the labels that each got.

#1009 Fix lack of idempotency in foreman_smartproxy_host provider
  lib/puppet/provider/foreman_smartproxy_host/rest_v3.rb
  spec/unit/foreman_smartproxy_host_rest_v3_spec.rb
Labels: Needs testing

#1010 Fixes #34161 - Run apipie:cache:index after db:migrate
  manifests/database.pp
Labels: Needs testing, Bug

#1011 Fixes #34089 - Add trusted proxies setting
  manifests/init.pp
  manifests/params.pp
  spec/classes/foreman_spec.rb
  templates/settings.yaml.erb
Labels: Needs testing, Enhancement
