Repository theforeman/puppet-foreman, pull requests merged in 2022-02, with the labels that each got.

#1027 puppet/extlib: Allow 6.x
  metadata.json
Labels: Needs testing, Enhancement

#1016 Introduce foreman::settings_fragment
  manifests/config.pp
  manifests/config/apache.pp
  manifests/settings_fragment.pp
  spec/defines/foreman_settings_fragment_spec.rb
Labels: Needs testing, Enhancement

#1026 Release 19.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#1029 release 19.2.1
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed
