Repository theforeman/puppet-foreman, pull requests merged in 2022-05, with the labels that each got.

#1050 Release 19.2.2
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#1046 Fixes #34602 - restart services after plugin installation
  manifests/init.pp
  spec/classes/foreman_spec.rb
Labels: Needs testing, Enhancement

#1053 derive base_url from foreman-proxy/settings.yml by default
  lib/puppet/provider/foreman_resource/rest_v3.rb
  spec/unit/foreman_resource_rest_v3_spec.rb
Labels: Needs testing
