Repository theforeman/puppet-foreman, pull requests merged in 2022-10, with the labels that each got.

#1093 Fixes #35685 - allow setting GssapiLocalName to Off
  manifests/config.pp
  manifests/init.pp
  spec/classes/foreman_config_ipa_spec.rb
  templates/auth_gssapi.conf.erb
Labels: Enhancement

#1089 Convert per_page in foreman::foreman to string
  lib/puppet/functions/foreman/foreman.rb
Labels: Bug

#1083 Refs #35473 - Configure Apache for API extlogin
  templates/auth_gssapi.conf.erb
  templates/lookup_identity.conf.erb
  templates/settings-external-auth.yaml.erb
Labels: Needs testing
