Repository theforeman/puppet-foreman, pull requests merged in 2022-08, with the labels that each got.

#1071 Use Integer type for vhost ssl_verify_depth
  manifests/config/apache.pp
Labels: Needs testing, Enhancement

#1072 Release 21.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog

#1075 Allow puppetlabs/apache 8.x
  metadata.json
Labels: Needs testing, Enhancement

#1076 Add hammer plugin for ssh
  manifests/cli/ssh.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/cli_plugins_spec.rb
Labels: Needs testing, Enhancement

#1074 Fixes #35356 - Don't proxy /server-status
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
Labels: Needs testing, Enhancement

#1079 Release 21.1.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog

#1081 drop support for host_reports, the plugin was dropped
  manifests/cli/host_reports.pp
  manifests/plugin/host_reports.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/cli_plugins_spec.rb
  spec/classes/plugin/host_reports_spec.rb
Labels: Needs testing, Backwards incompatible

#1078 Fixes #33956 - serve static assets directly via Apache
  README.md
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
Labels: Needs testing, Backwards incompatible

#1080 Drop /pulp2 and /streamer from no_proxy_uris
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
Labels: Needs testing, Backwards incompatible
