Repository theforeman/puppet-foreman, pull requests merged in 2022-06, with the labels that each got.

#1056 Fixes #34977: Drop apipie_dsl:cache generation
  manifests/database.pp
  manifests/init.pp
  manifests/plugin.pp
  spec/classes/foreman_database_spec.rb
  spec/classes/foreman_spec.rb
Labels: Needs testing, Not yet reviewed, Backwards incompatible

#1059 Add foreman plugin for git_templates
  manifests/plugin/git_templates.pp
  spec/classes/plugin/git_templates_spec.rb
Labels: Needs testing

#1057 Add foreman plugin for scc_manager
  manifests/plugin/scc_manager.pp
  spec/classes/plugin/scc_manager_spec.rb
Labels: Needs testing

#1058 Add foreman plugin for vault
  manifests/plugin/vault.pp
  spec/classes/plugin/vault_spec.rb
Labels: Needs testing

#1054 add foreman_global_parameter type
  lib/puppet/provider/foreman_global_parameter/rest_v3.rb
  lib/puppet/type/foreman_global_parameter.rb
  spec/acceptance/foreman_global_parameter_spec.rb
  spec/unit/provider/foreman_global_parameter/rest_v3_spec.rb
  spec/unit/type/foreman_global_parameter_spec.rb
Labels: Needs testing

#1065 Release 20.2.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing

#1066 Stop accepting UNSET as a value and rewrite db.yml to EPP
  manifests/config.pp
  manifests/database/postgresql.pp
  manifests/init.pp
  spec/classes/foreman_spec.rb
  templates/database.yml.epp
  templates/database.yml.erb
Labels: Needs testing, Backwards incompatible

#1060 Add foreman plugin for netbox
  manifests/plugin/netbox.pp
  spec/classes/plugin/netbox_spec.rb
Labels: Needs testing, Enhancement
