Repository theforeman/puppet-foreman, pull requests merged in 2022-03, with the labels that each got.

#1031 Allow puppetlabs/postgresql 8.x
  metadata.json
Labels: Needs testing

#1032 Switch to gha-puppet for CI
  .github/workflows/ci.yml
  .sync.yml
  Gemfile
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Modulesync

#1034 Use the new GPG key for Debian packages
  manifests/repos/apt.pp
  spec/defines/foreman_repos_apt_spec.rb
Labels: Needs testing, Bug

#1030 Refs #34505 - Add hammer plugin for foreman_host_reports
  manifests/cli/host_reports.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/cli_plugins_spec.rb
Labels: Needs testing, Not yet reviewed, Enhancement

#1036 metadata.json: Use https URL to git repo
  metadata.json
Labels: Needs testing, Bug
