Repository theforeman/puppet-foreman, pull requests merged in 2022-01, with the labels that each got.

#1014 Pin rdoc to < 6.4
  Gemfile
Labels: Needs testing, Not yet reviewed, skip-changelog

#1013 Refs #34089 - Work around Kafo type parsing bug
  manifests/init.pp
Labels: Needs testing

#1015 foreman::repo: use the package resource 'ensure' parameter to specify the desired ruby stream
  manifests/repo.pp
  spec/classes/foreman_repo_spec.rb
Labels: Needs re-review, Needs testing

#1002 Add basic `foreman_hostgroup` type
  README.md
  lib/puppet/provider/foreman_hostgroup/rest_v3.rb
  lib/puppet/type/foreman_host.rb
  lib/puppet/type/foreman_hostgroup.rb
  lib/puppet/type/foreman_instance_host.rb
  lib/puppet/type/foreman_smartproxy.rb
  lib/puppet/type/foreman_smartproxy_host.rb
  lib/puppet_x/foreman/common.rb
  spec/acceptance/foreman_hostgroups_spec.rb
  spec/types/foreman_hostgroup_spec.rb
  spec/unit/foreman_hostgroup_rest_v3_spec.rb
Labels: Needs testing, Enhancement

#960 Accept Datatype Sensitive for all Secrets
  lib/puppet/provider/foreman_config_entry/cli.rb
  manifests/cli.pp
  manifests/database.pp
  manifests/init.pp
  manifests/plugin.pp
  manifests/plugin/supervisory_authority.pp
  spec/classes/foreman_spec.rb
  spec/classes/plugin/supervisory_authority_spec.rb
  templates/hammer_root.yml.epp
Labels: Needs testing, Enhancement

#1019 Revert "Accept Datatype Sensitive for all Secrets"
  lib/puppet/provider/foreman_config_entry/cli.rb
  manifests/cli.pp
  manifests/database.pp
  manifests/init.pp
  manifests/plugin.pp
  manifests/plugin/supervisory_authority.pp
  spec/classes/foreman_spec.rb
  spec/classes/plugin/supervisory_authority_spec.rb
  templates/hammer_root.yml.epp
Labels: Needs testing

#1020 Fixes #34308 - Explicitly notify db:seed from db:migrate
  manifests/database.pp
Labels: Needs testing

#1021 Release 19.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#1024 Release 19.1.1
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog

#1023 Explicitly enable the foreman dnf module on Foreman 3.2+
  manifests/repo.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/foreman_repo_spec.rb
Labels: Needs testing
