Repository theforeman/puppet-foreman, pull requests merged in 2022-04, with the labels that each got.

#1039 Release 19.3.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog

#1040 Add Foreman Google plugin
  manifests/plugin/google.pp
  spec/classes/plugin/google_spec.rb
Labels: Needs testing

#1042 Fixes #34640 - Drop apipie:cache:index
  manifests/database.pp
  manifests/init.pp
  manifests/plugin.pp
  spec/classes/foreman_database_spec.rb
  spec/classes/foreman_spec.rb
Labels: Needs testing

#1045 Fixes #34824 - properly restart foreman when puma config changed
  manifests/service.pp
  spec/acceptance/foreman_service_spec.rb
  spec/classes/foreman_service_spec.rb
Labels: Needs testing, Bug

#1044 Release 20.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, skip-changelog
