Repository theforeman/puppet-foreman, pull requests merged in 2023-02, with the labels that each got.

#1106 Fixes #36028 - ensure compressed assets are returned if available
  files/_assets.conf.erb
Labels: Bug

#1104 bump puppet/systemd to < 5.0.0
  metadata.json
Labels: Enhancement

#1109 Fixes #36037 - Manage Redis service for Redis cache
  manifests/config.pp
  spec/acceptance/foreman_basic_spec.rb
  spec/classes/foreman_spec.rb
  templates/settings.yaml.erb
Labels: Enhancement

#1112 Release 22.2.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#1110 Bump puppetlabs/apache to < 10.0.0
  metadata.json
Labels: Enhancement
