Repository theforeman/puppet-foreman, pull requests merged in 2023-10, with the labels that each got.

#1135 Fixes #36812 - allow setting (fc)ct_location
  manifests/init.pp
  spec/classes/foreman_spec.rb
  templates/settings.yaml.erb
Labels: Enhancement

#1136 Release 23.2.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#1134 Fixes #36801: Make Redis the default cache type
  manifests/init.pp
  spec/classes/foreman_spec.rb
Labels: Backwards incompatible
