Repository theforeman/puppet-foreman, pull requests merged in 2023-11, with the labels that each got.

#1133 Update gems to support testing Puppet 8
  .github/workflows/ci.yml
  .gitignore
  CONTRIBUTING.md
  Gemfile
Labels: Modulesync

#1138 Mark compatible with puppet-extlib 7.x
  metadata.json
Labels: Not yet reviewed, Enhancement

#1141 Drop deprecated non-namespaced functions
  lib/puppet/parser/functions/foreman.rb
  lib/puppet/parser/functions/smartvar.rb
  spec/functions/foreman_spec.rb
  spec/functions/smartvar_spec.rb
Labels: Backwards incompatible

#1143 Mark compatible with puppetlabs/postgresql 10.x
  metadata.json
Labels: Enhancement

#1144 Release 24.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#1145 Add hammer-cli-foreman-rh-cloud package
  manifests/cli/rh_cloud.pp
  spec/acceptance/foreman_cli_plugins_spec.rb
  spec/classes/cli_plugins_spec.rb
Labels: Enhancement

#1146 Release 24.1.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
