Repository theforeman/puppet-foreman, pull requests merged in 2024-05, with the labels that each got.

#1162 Allow puppet/systemd 7.x
  metadata.json
Labels: Not yet reviewed, Enhancement

#1155 Refs #37212 - Drop foreman_setup plugin support
  manifests/plugin/setup.pp
  spec/classes/plugin/setup_spec.rb
Labels: Waiting on contributor, Backwards incompatible

#1163 Allow puppet/redis 11.x
  metadata.json
Labels: Enhancement

#1165 Release 25.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog
