Repository theforeman/puppet-foreman, pull requests merged in 2024-09, with the labels that each got.

#1181 Unset all possible dash/underscore combinations of REMOTE_USER
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
Labels: Bug

#1183 Release 25.2.1
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#1182 Unset all possible dash/underscore combinations of REMOTE_USER
  manifests/config/apache.pp
  spec/classes/foreman_config_apache_spec.rb
Labels: Bug, Stable branch

#1184 Release 24.2.1
  CHANGELOG.md
  metadata.json
Labels: skip-changelog, Stable branch

#1185 Fixes #37761 - use ProxyPass and upgrade=websocket where possible
  manifests/config/apache.pp
  manifests/plugin/remote_execution/cockpit.pp
  spec/classes/foreman_config_apache_spec.rb
  spec/classes/plugin/remote_execution_cockpit_spec.rb
  templates/cockpit-apache-ssl-rewrite.conf.erb
  templates/cockpit-apache-ssl.conf.erb
Labels: Needs re-review, Bug
