Repository theforeman/puppet-foreman, pull requests merged in 2025-08, with the labels that each got.

#1230 Pin puppet-apt since it dropped Puppet 7
  .fixtures.yml
Labels: Not yet reviewed

#1231 Release 27.0.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#1232 install amcheck extension for PostgreSQL
  manifests/database/postgresql.pp
Labels: Enhancement
