Repository theforeman/puppet-foreman, pull requests merged in 2025-09, with the labels that each got.

#1233 Release 27.1.0
  CHANGELOG.md
  metadata.json
Labels: skip-changelog

#1234 Allow puppet/redis 12.x
  metadata.json
Labels: Not yet reviewed, Enhancement

#1236 Allow puppetlabs/apache 13.x
  metadata.json
Labels: Enhancement
